Validation spec
EvansSnave/Blog_app_rails pull request #3
Opened 2023-12-02 22:55 UTC by EvansSnave

Add the following validations:
For the User model:
Name must not be blank.
PostsCounter must be an integer greater than or equal to zero.
For the Post model:
Title must not be blank.
Title must not exceed 250 characters.
CommentsCounter must be an integer greater than or equal to zero.
LikesCounter must be an integer greater than or equal to zero.
Add unit specs for all of your models' methods and validations.

2023-12-02 23:15 UTC, V-Blaze requested changes
## Hi @, 

## Required changes 🖊️ 
# Almost there 🟡 🟦 🟨 

![almost-there](https://user-images.githubusercontent.com/107632780/229242540-644ade4a-fe15-4f4c-a38b-6ded70cc4e8b.gif)


Great work so far, You have come a long way, keep moving forward👏 👍  
You've done well implementing the project requirements, but there are still some issues I think you need to improve on. 😄 👋 


 ## Highlights
- Wrote tests for custom methods✔
- SOme tests are passing👋 
-  Correct git flow✔

 ## Required Changes ♻️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-12-02 23:15 UTC, V-Blaze commented on app/models/user.rb
> +end
- You have done great so far :+1: But there are a few requirements you need to meet before moving to the next milestone. :+1: :100: 

- - Requirement Screenshot:

![Selection_054](https://github.com/EvansSnave/Blog_app_rails/assets/107632780/6c9925f5-415a-4c7c-ab37-43bf9ecccc30)

- [ ] According to the project requirement, you need to add validations to the user model to make sure that a name is always present t when a user is created and also that PostsCounter must be an integer greater than or equal to zero. Currently, you haven't implemented this. I suggest you do as it is part of the requirement, :+1: :+1: :100: Here is a snippet of what the first validation could look like:
```ruby
validates :name, presence: true
```

2023-12-02 23:15 UTC, V-Blaze commented on app/models/post.rb
> +  after_save :update_posts_counter!
- - Screenshot reference:

![Selection_055](https://github.com/EvansSnave/Blog_app_rails/assets/107632780/bd1216a1-682e-45d7-8e5f-fcf0d743027b)

- [ ] Just as I pointed out above on the `Users model`, the post counter should have some validation according to the project requirement as i have shown in the screenshot above too. :+1: :+1: I suggest you look at the requirements and add all the validation to the post model. Here is a snippet of the `CommentsCounter must be an integer greater than or equal to zero.` validation could look like. :+1: 

````ruby
validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
```

2023-12-02 23:15 UTC, V-Blaze commented on spec/models/user_spec.rb
> +  end
- [ ] You have done great writing the model specs and covering all the validations specs and custom methods, but looking at the screenshot below, you can see that only `3 tests` are passing the rest of the tests are failing. I'll suggest you fix these as all the tests are meant to pass. :+1: :smile: :wave: 

- - Screenshot:
![Screenshot from 2023-12-03 00-12-33](https://github.com/EvansSnave/Blog_app_rails/assets/107632780/1fac2a96-c981-4738-8a6d-0f70e254388c)

2023-12-03 00:02 UTC, Strangeal approved these changes
Hi @EvansSnave, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉 

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjk5MjNhMmYyM2RjZmZmNWRkNjA3OWNmNGFhMjI4NDViOTg4N2UzNyZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PXM/x3l1BWfB85i2uU8nKK/giphy.gif)


## Highlights
- Added validation to models ✅ 
- Fixed failing test ✅ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-04-07 19:44 UTC, merged